# Generated by Django 4.0.1 on 2023-01-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Total_Time',
            field=models.IntegerField(default='30'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.IntegerField(default='15'),
        ),
    ]
