# Generated by Django 4.0.1 on 2023-01-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_recipe_total_time_alter_recipe_prep_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('veg', 'veg'), ('Non_veg', 'Non_veg')], default='Non_veg', max_length=10),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
